### ISSUE TITLE
List of GUI Bugs From the Redesign

### ISSUE THREAD

**Issue by Tloru** [HermesMessenger/Hermes#68] opened 2019-02-14 03:29 UTC
Here's a list of small bugs / design inconsistencies I've found while testing the webapp version of hermes (Dark Mode, ChromeOS 72.0.3626.96 on MacOS Mojave 10.14, Macbook Air, Early 2015).

long comments will clip into the time:
![screen shot 2019-02-14 at 10 20 12 am](https://user-images.githubusercontent.com/17747189/52760506-54314280-3042-11e9-8ee5-ef8f632feced.png)

Some comments clip into others, or the picture is not aligned with the username:
![screen shot 2019-02-14 at 10 20 31 am](https://user-images.githubusercontent.com/17747189/52760529-6612e580-3042-11e9-9ba0-51fb8bbb9c8c.png)
![screen shot 2019-02-14 at 10 20 38 am](https://user-images.githubusercontent.com/17747189/52760531-6a3f0300-3042-11e9-968c-8808b2f98e99.png)

The send and settings button are hidden, and don't stick to the bottom when scrolling:
![screen shot 2019-02-14 at 10 20 50 am](https://user-images.githubusercontent.com/17747189/52760589-ad00db00-3042-11e9-83a8-e4199fd72a24.png)

Comments seem to load with fixed line breaks:
![screen shot 2019-02-12 at 6 14 53 pm](https://user-images.githubusercontent.com/17747189/52760693-11bc3580-3043-11e9-85a4-a8d3987d78ab.png)

It seems to be loading a newer version, but reverts to the old one, with some unresolved details. Seems to be limited to dark mode, light mode runs fine.

**Comment by Tloru** [comment] 2019-02-14 05:14
Here are some design inconsistencies I've found with the new light mode:

Large gap on left side of screen:
![screen shot 2019-02-14 at 12 12 12 pm](https://user-images.githubusercontent.com/17747189/52764248-d117e880-3051-11e9-918a-b6548d299bd6.png)

Send arrow is floating in the wrong place:
![screen shot 2019-02-14 at 12 13 33 pm](https://user-images.githubusercontent.com/17747189/52764295-09b7c200-3052-11e9-9409-059725273f76.png)

**Comment by spaceface777** [comment] 2019-02-14 09:36
-  ## Dark theme bugs
    - They occur because only the light theme CSS is implemented, and the dark theme still uses the old CSS

-  ## Light theme bugs
    - The gap on the left side is there on purpose, we are adding message bubbles on the left to show messages sent by other users (like in other messaging apps) and that is there to separate both sides

- The send arrow is in the wrong place because we currently don't resize the input box, so usernames longer than 1 character break it. 

***

-  ## Other bugs
    - Deleting and editing messages doesn't work.

**Comment by Tloru** [comment] 2019-02-14 11:50
I fixed most of the dark theme bugs with my proposed pull request.

**Comment by spaceface777** [comment] 2019-02-14 20:28
The arrow getting pushed down bug is now fixed. 

About your pull request, since we are still working on the new design and have a lot still left to do, I think it's better to wait until the entire light theme is fixed before starting on the dark theme.

**Comment by Tloru** [comment] 2019-02-14 21:59
Ah, ok. When the light theme's 100%, let me know so I can get started on the dark theme.

**Comment by spaceface777** [comment] 2019-02-15 09:33
- Deleting and editing messages works now.
 - Chat bubbles for other people's messages added

**Comment by Tloru** [comment] 2019-02-15 11:57
@spaceface777 I've updated the dark theme css to match. 👍

**Comment by Tloru** [comment] 2019-02-15 11:57
still needs some work to make it fully consistent, though. Especially the send/settings icons, and the settings window.

**Comment by spaceface777** [comment] 2019-02-18 07:54
#74 is another UI bug in the redesign.

**Comment by Tloru** [comment] 2019-02-18 12:43
kk. should we just keep this issue as a semi-permanent list of all GUI issues instead of opening new ones?

**Comment by spaceface777** [comment] 2019-02-18 15:42
I think this issue should be for all GUI issues *related to / caused by the redesign*.

**Comment by Tloru** [comment] 2019-02-19 00:19
whoops, sorry, I didn't see your message. Changing it back to what you wrote.

**Comment by Tloru** [comment] 2019-02-19 00:20
Another bug: When opening Hermes, the Website doesn't scroll to the bottom, most recent message.

**Comment by KeyKoder** [comment] 2019-02-19 06:17
It did that but my commit was in a previous version. I think @ThePerkinrex
will try to fix my commit.

**Comment by spaceface777** [comment] 2019-02-21 14:54
I've been improving the layout and I think there are no bugs left, so I think this is ready to be closed. If anyone sees any other UI bug, please post it here

**Closed** 2019-03-18 17:56 UTC
Labels: Bug, Med. importance, Web client
