### ISSUE TITLE
Add ability to tag (@) other users

### ISSUE THREAD

**Issue by ThePerkinrex** [HermesMessenger/Hermes#13] opened 2018-11-08 21:25 UTC

**Comment by spaceface777** [comment] 2018-11-09 08:34
Duplicate of #6

**Comment by spaceface777** [comment] 2018-11-20 17:11
> Duplicate of #6

In the end, although #6 had two parts, we only implemented the second one and not this one.

**Comment by Tloru** [comment] 2019-02-28 11:44
mentioning would just be quoting without the reference message, right? Couldn't we just extend the quote regex and update on the GUI?

**Comment by ThePerkinrex** [comment] 2019-02-28 13:21
Yes, probably that could be the solution

**Comment by ThePerkinrex** [comment] 2019-02-28 13:22
I will look into it

**Comment by spaceface777** [comment] 2019-02-28 14:19
Another option would be to add another regex (`@([^ ]+)` for example), check if the matched string is in the `user_colors` object, and if it is replace the whole thing with a formatted version of the string: 

```html
<b style="color: #color">regex[1]</b>
```

**Comment by spaceface777** [comment] 2019-03-05 20:18
Most of the work has been done in 3a28db4.

**Closed** 2019-03-07 17:25 UTC
Labels: Hermes Mobile, Low importance, New idea, Web client
