### ISSUE TITLE
Message size on mobile

### ISSUE THREAD

**Issue by spaceface777** [HermesMessenger/Hermes#42] opened 2018-12-02 09:06 UTC
There are a few problems with message sizes on mobile:

 - The time is too small to read
 - The first few messages are very small, but then it corrects itself after a few. 
    - If you rotate the device, all of them show with the same (big) font size. 

![Screenshot](https://user-images.githubusercontent.com/12110214/49337784-2464c800-f619-11e8-9209-dd976c60d415.png)

**Comment by ThePerkinrex** [comment] 2018-12-02 14:33
Duplicate of #15

**Closed by ThePerkinrex** 2018-12-02 14:33 UTC
Labels: Bug, Med. importance, Web client
